Biotech 1
Ludeon/RimWorld-Czech pull request #33
Opened 2023-11-25 10:54 UTC by lordfanger

Úpravy překladu biotechu, většinou kosmetické

2023-11-25 11:59 UTC, Axolotllz commented
10/10

2023-11-25 14:05 UTC, lordfanger reviewed
github feedback

2023-11-26 10:01 UTC, Axolotllz requested changes

2023-11-26 10:43 UTC, lordfanger reviewed
github feedback

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/Items_Various.xml
> +  <ArchiteCapsule.description>Malá kapsle obsahující archity, mikroskopické stroje vytvořené superinteligentními archoteky. Tyto stroje jsou schopné psychických i fyzických činností, které se zdají n
```suggestion
  <ArchiteCapsule.description>Malá kapsle obsahující archity, mikroskopické stroje vytvořené superinteligentními archoteky. Tyto stroje jsou schopné psychických i fyzických činností, které se zdají nemožné dnešním vědcům. Jako s jakoukololi achrotechnologií, žádný člověk jí není schopen vytvořit. Můžeme pouze použít nalezené části které si archotechové vytvořili pro svoje nedozírné potřeby.\n\nTato kapsle jako taková je k ničemu, ale může být použita v genovém sestavovači pro vytvoření nového archoteckého genovštipovače. To vyžaduje mít odemčený výzkum archogenetiky a genobalík obsahující architský gen. Architské genobalíky mohou být koupeny od obchodníků.</ArchiteCapsule.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/Items_Various.xml
> +  <Xenogerm.description>Speciální bioligický orgán obsahující jeden nebo více implantovatelných xenogenů.\n\nPo implantování modifikuje geny hostitele, jeho vzhled, a fenotypický vývoj použitím virů,
```suggestion
  <Xenogerm.description>Speciální biologický orgán obsahující jeden nebo více implantovatelných xenogenů.\n\nPo implantování modifikuje geny hostitele, jeho vzhled, a fenotypický vývoj použitím virů, hormonů a biosyntetických léků či mechanitů. Podle vštípených xenogenů se hostiteli vyvinou různé rysy a schopnosti, transformující je na odlišný lidský xenotyp.\n\nVštípení genovštipovače je velmi traumatizující proces. Po vštípení genovštipovače bude pacient uvázán na lůžko na několik dní, zatímco bude probíhat transformace.\n\nPři skladování a přenosu jsou genovštipovače uložené ve speciálních zapečetěných schránkách.</Xenogerm.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/Races_Mechanoids_Medium.xml
> +  <Mech_Scorcher.description>Mechanoid určený pro boj na krátké vzdálenosti s jeho spalujícími útoky. Jeho ohniví útok má sice velmi krákou vzdálenost, ale je schopný zapálit velké skupiny nepřátel a
```suggestion
  <Mech_Scorcher.description>Mechanoid určený pro boj na krátké vzdálenosti s jeho spalujícími útoky. Jeho ohnivý útok má sice velmi krátkou vzdálenost, ale je schopný zapálit velké skupiny nepřátel a spalujícím ohněm narušit jejich činnosti.</Mech_Scorcher.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/Races_Mechanoids_SuperHeavy.xml
> +  <Mech_Diabolus.description>Extratěžký mechanoid s extrémně silným peklosférovým kanónem. Vytvořen pro obléhání, jeho kanón se nabíjí relativně dlouho, ale je schopen roztopit beton a vypařit kosti.
nevím, jestli přebíjí.. ale roztavit by klidně šlo
to roztopit ale taky nezní tam moc špatně, na RimWorldštinu
@morticinus co ty na to?

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThoughtDef/Thoughts_Memory_Special.xml
>    <IngestedHemogenPack.stages.ingested_hemogen_pack.description>Snědl{PAWN_pronoun} jsem balíček hemogenu. Možná mě to udrží na živu ale bylo to absolutně odporné.</IngestedHemogenPack.stages.ingeste
```suggestion
  <IngestedHemogenPack.stages.ingested_hemogen_pack.description>Snědl{PAWN_pronoun} jsem balíček hemogenu. Možná mě to udrží naživu ale bylo to absolutně odporné.</IngestedHemogenPack.stages.ingested_hemogen_pack.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThoughtDef/Thoughts_Situation_Genes.xml
> +  <!-- LF: Gen Pessimist ještě není pželožen. -->
koukal jsem do hry a jsou to odkazy na geny v `GeneDefs_Spectrum.xml` a ty nejsou zatím ještě vůbec přeloženy vůbec a tudíž ani součástí tohoto opravného commitu

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/WorkGiverDef/WorkGivers.xml
> +  <CarryToSubcoreScanner.label>odnáší do subjádrovéhu snímače</CarryToSubcoreScanner.label>
```suggestion
  <CarryToSubcoreScanner.label>odnáší do subjádrového snímače</CarryToSubcoreScanner.label>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/XenotypeDef/XenotypeDefs.xml
> +  <Dirtmole.description>Se šedou kůží adaptovanou na umělé světlo se krtkouni vyžívají ve stísněných a tmavých prostorech, kde se souboje a cestování odehrávají na relativně krátkých vzdálenostech. J
```suggestion
  <Dirtmole.description>Se šedou kůží adaptovanou na umělé světlo se krtkouni vyžívají ve stísněných a tmavých prostorech, kde se souboje a cestování odehrávají na relativně krátkých vzdálenostech. Jsou velmi schopní v kopání a těžení. Za to ale trpí pokud jsou vystaveni slunečnímu světlu, které je spaluje. Také na větších otevřených prostranstvých jim nepomáhá jejich pomalá rychlost ani krátkozrakost.\n\nPoté, co selhaly první podzemní kolonie na stres a ponorkovou nemoc, kolonizační agentury začaly vývoj na upraveném lidském genomu, jehož nositelé jsou schopni žít ve stísněných prostorech bez slunečního světla. Členům tohoto xenotypu se hovorově říká krtkouni. Už je to dlouho, co krtkouni opustili jejich původní podzemní doupata a začali vládnout mnoha dalším uzavřeným prostorům na světě. Často se nachází v hlubokých dolech, stísněných primitivních vesmírných lodí či po miliardách v hlubinách nezpočetných městských světů.</Dirtmole.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/XenotypeDef/XenotypeDefs.xml
> +  <Sanguophage.description>Sanguofágové jsou archotecky upravený xenotyp lidí. Poháněni archity, jejich schopnosti sahají až za hranice obyčejného genetického inženýrství. Jsou mentálně na výši, nadp
já to chápu tak, že `archotech-enhanced xenohuman` je myšleno "jak, archotecky" místo "kým, Archoteky".. ale je to asi tak nějak jedno. :)

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/XenotypeDef/XenotypeDefs.xml
> +  <Sanguophage.description>Sanguofágové jsou archotecky upravený xenotyp lidí. Poháněni archity, jejich schopnosti sahají až za hranice obyčejného genetického inženýrství. Jsou mentálně na výši, nadp
```suggestion
  <Sanguophage.description>Sanguofágové jsou archotecky upravený xenotyp lidí. Poháněni archity, jejich schopnosti sahají až za hranice obyčejného genetického inženýrství. Jsou mentálně na výši, nadpřirozeně krásní a v boji jsou schopni vystřelit smrtící ostny a vyléčit spojence. Nestárnou ani přirozeně neumírají a nikdy nepodlehnou nemoci či otrávě. Sanguofágové jsou schopni vytvořit další sanguofágy použitím jejich vlastní genovštipovací metody.\n\nSanguofágové musí pravidelně konzumovat hemogen z lidské krve a také musí pravidelně mrtvospát. Jsou náchylní na spálení ohněm a omezeni slunečním zářením.\n\nPrvní sanguofágové se poprvé zjevili několik tisíc let zpět, když lord Varan-Dur se chtěl pokusit ovládnout hyperinteligentní archotechnologii, ale namísto toho byl transformován v prvního novodobého sanguofága. Všichni sanguofágové jsou jeho potomci. Od té doby byli sanguofágové loveni pro jejich přílišnou moc a pro jejich potřebu konzumovat lidskou krev. Tím že vzhledově jsou velmi podobní obyčejníkům tak často žijí v ustraní mezi obyčejnými lidmi.\n\nJejich počty jsou neznámé a proto si někteří myslí že jsou pouze legendami. Jiní zase věří v to že sanguofágové ovládají chod celé lidské civilizace. Tradují se příběhy o lordech ovládající miliardy ze své břidlicové vesmírné stanice či o ukrývajících sanguofázích, plánující krvavé oběti ze skrytých konferencí z nejhlubšího podsvětí městských světů.</Sanguophage.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/XenotypeDef/XenotypeDefs.xml
> +  <Waster.descriptionShort>Jsou agresivní, toxinům imuní, nemocem odolní a mohou konzumovat psychit a budíček bez negativních efektů. Vedlejší efekt jejich metabolismus je potřeba konzumovat psychit,
```suggestion
  <Waster.descriptionShort>Jsou agresivní, toxinům imunní, nemocem odolní a mohou konzumovat psychit a budíček bez negativních efektů. Vedlejší efekt jejich metabolismus je potřeba konzumovat psychit, který má většinou formu vločky nebo jája.</Waster.descriptionShort>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/Keyed/Dialog_StatsReports.xml
> +  <StatsReport_DevelopmentStageDesc_ChildPart2>Posutupně co dítě stárne, bude mít příležitosti si získat vášně a rysy.\n\nDěti mají svoje specifické způsoby učení a mohou si obléknout jenom oblečení
```suggestion
  <StatsReport_DevelopmentStageDesc_ChildPart2>Postupně co dítě stárne, bude mít příležitosti si získat vášně a rysy.\n\nDěti mají svoje specifické způsoby učení a mohou si obléknout jenom oblečení dětské velikosti.\n\nU lidských dětí, po dosažení 13 let se z nich prakticky stávají dospělí.</StatsReport_DevelopmentStageDesc_ChildPart2>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/Keyed/Dialogs_Various.xml
> +  <ConfirmDisassemblingMech>Opreavdu chceš rozebrat {lookup: {0}; case\singular; 4}?\n\nRozebráním {lookup: {0}; case\singular; 2} získáme</ConfirmDisassemblingMech>
```suggestion
  <ConfirmDisassemblingMech>Opravdu chceš rozebrat {lookup: {0}; case\singular; 4}?\n\nRozebráním {lookup: {0}; case\singular; 2} získáme</ConfirmDisassemblingMech>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/Keyed/Dialogs_Various.xml
> +  <RecombineDurationDesc>Jak dlouho bude trvat průměrnému kolonistovy zkombinovat vybrané geny do genovštipovače. Zakomponovávací čas se prodlužuje s celkovou komplexitou genů v genovštipovači.</Reco
```suggestion
  <RecombineDurationDesc>Jak dlouho bude trvat průměrnému kolonistovi zkombinovat vybrané geny do genovštipovače. Zakomponovávací čas se prodlužuje s celkovou komplexitou genů v genovštipovači.</RecombineDurationDesc>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/Keyed/Misc_Gameplay.xml
> +  <WrongDevelopmentalStageForClothing>TODO</WrongDevelopmentalStageForClothing>
možná spíše "z důvodu".. kdo ví.. to bude chtít se podívat na ten text přímo do hry, jak to bude vypadat

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/RangedMechanoid_Heavy.xml
> +  <Gun_HellsphereCannon.description>Extrémně vysokoenergický kanón vytvořený pro obléhání. Při zaměřování musí držet cíl na mušce několik vteřin, zatímco se nabíjí a předtím než vypustí devastující t
no, tsunami je taková opravdu větší vlna.. a tenhle peklokanón je pořádný kanón
asi bych to ale nechal na našeho @morticinus co si o tom myslí

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/RangedIndustrial.xml
> +  <Weapon_GrenadeTox.description>Granáty naplněné zkapalněným jedovatým plynem. Po dopadu se přilepý k zemi a začne na několik sekund vypouštět jedovatý plyn.\n\nPlyn pálí v plicích a očích a způsobu
```suggestion
  <Weapon_GrenadeTox.description>Granáty naplněné zkapalněným jedovatým plynem. Po dopadu se přilepí k zemi a začne na několik sekund vypouštět jedovatý plyn.\n\nPlyn pálí v plicích a očích a způsobuje krátkodobé lapání po dechu a částečné oslepení. Dlouhodobé vystavení jedovatému plynu začne způsobovat toxické nahromadění a následně i smrt.</Weapon_GrenadeTox.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/RangedIndustrial.xml
> +  <Weapon_GrenadeTox.description>Granáty naplněné zkapalněným jedovatým plynem. Po dopadu se přilepý k zemi a začne na několik sekund vypouštět jedovatý plyn.\n\nPlyn pálí v plicích a očích a způsobu
sekundy jsou v pořádku, používají se všude jinde v překladu

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/RangedIndustrial.xml
> +  <Gun_ToxbombLauncher.description>Samonabíjecí nízkotlakový granátomet pro jedoplynové granáty. Po dopadu se jedoplynový granát přilepý k zemi a začne na několik sekund vypouštět jedovatý plyn.\n\nP
```suggestion
  <Gun_ToxbombLauncher.description>Samonabíjecí nízkotlakový granátomet pro jedoplynové granáty. Po dopadu se jedoplynový granát přilepí k zemi a začne na několik sekund vypouštět jedovatý plyn.\n\nPlyn pálí v plicích a očích a způsobuje krátkodobé lapání po dechu a částečné oslepení. Dlouhodobé vystavení jedovatému plynu začne způsobovat toxické nahromadění a následně i smrt.</Gun_ToxbombLauncher.description>
```

2023-11-26 10:43 UTC, lordfanger commented on Biotech/DefInjected/ThingDef/RangedMechanoid_Heavy.xml
> +  <Gun_HellsphereCannon.description>Extrémně vysokoenergický kanón vytvořený pro obléhání. Při zaměřování musí držet cíl na mušce několik vteřin, zatímco se nabíjí a předtím než vypustí devastující t
```suggestion
  <Gun_HellsphereCannon.description>Extrémně vysokoenergický kanón vytvořený pro obléhání. Při zaměřování musí držet cíl na mušce několik sekund, zatímco se nabíjí a předtím než vypustí devastující tsunami energie. Jeho exploze je tak silná že je schopná roztavit beton v místě výbuchu. Žár této exploze zapálí cokoli nacházející se poblíž. Nemůže se zaměřit na příliš blízké cíle.</Gun_HellsphereCannon.description>
```

2024-01-19 15:19 UTC, merged